config/routes.rb
Rails.application.routes.draw do
  get 'subscriptions/new'

  get 'visitors/new'

  get 'content/new'

  get 'products/new'

  get 'registrations/new'

  get 'sessions/new'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/visitors', to: 'visitors#index'
  resources :users
  resources :visitors
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  include Payola::Plan

  has_many :users

  def redirect_path(subscription)
    '/'
  end

end

app/models/subscription_plan.rb
class SubscriptionPlan < ActiveRecord::Base
  include Payola::Plan
end

app/models/user.rb
class User < ActiveRecord::Base
    enum role: [:user, :admin, :basic, :classic, :modern]
    after_initialize :set_default_role, :if => :new_record?
    after_initialize :set_default_plan, :if => :new_record?
    # after_create :sign_up_for_mailing_list

    belongs_to :plan 
    validates_associated :plan

    def set_default_role
      self.role ||= :user
    end

    def set_default_plan
      self.plan ||= Plan.first
    end
    before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum:255 },
                      format: { with:VALID_EMAIL_REGEX},
                      uniqueness: { case_sensitive: false }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  before_action :authenticate_user!

  def silver
    redirect_to root_path, :notice => "Access denied." unless current_user.silver?
  end

  def gold
    redirect_to root_path, :notice => "Access denied." unless current_user.gold?
  end

  def platinum
    redirect_to root_path, :notice => "Access denied." unless current_user.platinum?
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :identify_product

  def show
    send_file @path, :disposition => "attachment; filename=#{@file}"
  end

  private
  def identify_product
    valid_characters = "^[0-9a-zA-Z]*$".freeze
    unless params[:id].blank?
      @product_id = params[:id]
      @product_id = @product_id.tr("^#{valid_characters}", '')
    else
      raise "Filename missing"
    end
    unless params[:format].blank?
      @format = params[:format]
      @format = @format.tr("^#{valid_characters}", '')
    else
      raise "File extension missing"
    end
    @path = "app/views/products/#{@product_id}.#{@format}"
    @file = "#{@product_id}.#{@format}"
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  include Payola::StatusBehavior
  before_action :cancel_subscription, only: [:destroy]

  def new
    if !params[:plan].nil?
      @plan = Plan.find_by!(stripe_id: params[:plan])
      puts "plan found"
      flash[:success] = "Found the plan!"
    else
      puts "plan not found"
      flash[:success] = "plan not found!"
    end
  end

  def create
    build_resource(sign_up_params)
    plan = Plan.find_by!(id: params[:user][:plan_id].to_i)
    resource.role = User.roles[plan.stripe_id] unless resource.admin?
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        subscribe
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        subscribe
      end
    else
      clean_up_passwords resource
      render json:
        {error: resource.errors.full_messages.to_sentence},
        status: 400
    end
  end

  def change_plan
    plan = Plan.find_by!(id: params[:user][:plan_id].to_i)
    unless plan == current_user.plan
      role = User.roles[plan.stripe_id]
      if current_user.update_attributes!(plan: plan, role: role)
        subscription = Payola::Subscription.find_by!(owner_id: current_user.id)
        Payola::ChangeSubscriptionPlan.call(subscription, plan)
        redirect_to edit_user_registration_path, :notice => "Plan changed."
      else
        flash[:alert] = 'Unable to change plan.'
        build_resource
        render :edit
      end
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:email,
    :password, :password_confirmation, :plan_id)
  end

  def subscribe
    return if resource.admin?
    params[:plan] = current_user.plan
    subscription = Payola::CreateSubscription.call(params, current_user)
    current_user.save
    render_payola_status(subscription)
  end

  def cancel_subscription
    subscription = Payola::Subscription.find_by!(owner_id: current_user.id, state: 'active')
    Payola::CancelSubscription.call(subscription)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      render 'visitors/index'
    else
      flash[:failure] = "Authentication Failed! user name and/or password incorrect!"
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
    if !params[:plan].nil?
      @plan = Plan.find_by!(stripe_id: params[:plan])
      puts "plan found"
      flash[:success] = "Found the plan!"
    else
      puts "plan not found"
      flash[:success] = "plan not found!"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    puts "in show"
    @user = User.find(params[:id])
    @plan = Plan.find(@user.plan_id)
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Subscriptions app!"
      render 'visitors/index'
    else
      render 'new'
    end
  end
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def create
    puts "******"
    puts params[:plan_id]
    @user = User.find_by(id: session[:user_id])
    @user.plan_id = params[:plan_id]
    @user.save
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Subscription Application"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_plan
    @current_user ||= User.find_by(id: session[:user_id])
    @current_plan = Plan.find_by(id: @current_user.plan_id)
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/content/basic.html.erb
<h1>Content#platinum</h1>
<p>Find me in app/views/content/basic.html.erb</p>

app/views/content/classic.html.erb
<h1>Content#platinum</h1>
<p>Find me in app/views/content/classic.html.erb</p>

app/views/content/modern.html.erb
<h1>Content#gold</h1>
<p>Find me in app/views/content/modern.html.erb</p>

app/views/content/new.html.erb
<h1>Content#new</h1>
<p>Find me in app/views/content/new.html.erb</p>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

app/views/static_pages/help.html.erb
<h1>Subscription Application Features</h1>
<p>
<br/>
1) As a user, I sign up and I am presented with My Subscription Page
<br/>
2) Password stored as hashed password using password_digest
<br/>
3) indexed on email for faster access during login
<br/>
4) regex validation for email for uniqueness and case-insensitvity
<br/>
5) validation for presence of email. didnt put validation for user as request.
<br/>
6) validation of email length
<br/>
7) Stripe integration for credit card payments
<br/>
8) Payola for subscription model using stripe
<br/>
9) User profile updated with subscribed plan
<br/>
10) Plan Upgrade
<br/>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Subscription application</h1>

  <h2>
    This is the Subscription Application by Deepika
  </h2>
  <% if logged_in? %>
    <h3>You are logged in</h3>
  <% else %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
  
</div>

app/views/subscriptions/new.html.erb
<br/>
<br/>
<%= render 'payola/transactions/stripe_header' %>

<%= form_tag(visitors_path(:id => @plan.id),
      class: 'payola-onestep-subscription-form',
      'data-payola-base-path' => '/payola',
      'data-payola-plan-type' => @plan.plan_class,
      'data-payola-plan-id' => @plan.id
  ) do |f| %>
  <span class="payola-payment-error"></span>
  Email:<br>
  <input type="email" name="stripeEmail" data-payola="email"></input><br>
  Card Number<br>
  <input type="text" data-stripe="number"></input><br>
  Exp Month<br>
  <input type="text" data-stripe="exp_month"></input><br>
  <%= hidden_field_tag :plan_id, @plan.id %>
  Exp Year<br>
  <input type="text" data-stripe="exp_year"></input><br>
  CVC<br>
  <input type="text" data-stripe="cvc"></input><br>
  <input type="submit"></input>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Subscribed To: <%= @plan.name if @plan.name %></p>
</div>
  <div class="row col-sm-12 plans">
    <div class="col-sm-2 well">
      <div class="plan"><h2>Basic</h2></div>
      <ul class="list-unstyled">
        <li>Private Party Access Alternate Fridays at Popular bars with 1 Guest</li>
      </ul>
      <h3>$19/month</h3>
      <% if @plan.name == 'Basic' %>
      <h3>Subscribed<h3>
      <% else %>
      <%= link_to "Subscribe", controller: "subscriptions", action: "new", plan: 'basic', :class => 'btn btn-primary' %>
      <% end %>
    </div>
    <div class="col-sm-2 well featured">
      <div class="plan featured-plan"><h2>Classic</h2></div>
      <ul class="list-unstyled">
        <li>Preferential access to SF restaurants</li>
      </ul>
      <h3>$99/month</h3>
      <% if @plan.name == 'Classic' %>
      <h3>Subscribed<h3>
      <% else %>
      <%= link_to "Subscribe", controller: "subscriptions", action: "new", plan: 'classic', :class => 'btn btn-primary' %>
      <% end %>
    </div>
    <div class="col-sm-2 well">
      <div class="plan"><h2>Modern</h2></div>
      <ul class="list-unstyled">
        <li>Private Lounge Access SFO</li>
        <li>Vip Access to Events and Concerts including chauffeur</li>
      </ul>
      <h3>$199/month</h3>
      <% if @plan.name == 'Modern' %>
      <h3>Subscribed<h3>
      <% else %>
      <%= link_to "Subscribe", controller: "subscriptions", action: "new", plan: 'modern', :class => 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

app/views/visitors/index.html.erb
  <div id="welcome" class="span7">
    <h1>Membership Site</h1>
  </div>
  <div class="row col-sm-12 plans">
    <div class="col-sm-2 well">
      <div class="plan"><h2>Basic</h2></div>
      <ul class="list-unstyled">
        <li>Private Party Access Alternate Fridays at Popular bars with 1 Guest</li>
      </ul>
      <h3>$19/month</h3>
      <%= link_to "Subscribe", controller: "subscriptions", action: "new", plan: 'basic', :class => 'btn btn-primary' %>
    </div>
    <div class="col-sm-2 well featured">
      <div class="plan featured-plan"><h2>Classic</h2></div>
      <ul class="list-unstyled">
        <li>Preferential access to SF restaurants</li>
      </ul>
      <h3>$99/month</h3>
      <%= link_to "Subscribe", controller: "subscriptions", action: "new", plan: 'classic', :class => 'btn btn-primary' %>
    </div>
    <div class="col-sm-2 well">
      <div class="plan"><h2>Modern</h2></div>
      <ul class="list-unstyled">
        <li>Private Lounge Access SFO</li>
        <li>Vip Access to Events and Concerts including chauffeur</li>
      </ul>
      <h3>$199/month</h3>
      <%= link_to "Subscribe", controller: "subscriptions", action: "new", plan: 'modern', :class => 'btn btn-primary' %>
    </div>
  </div>